name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln
    - name: Build
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -p:Configuration=Release
    - name: zip Assemblies
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerAsssemblies.zip $Env:GITHUB_WORKSPACE\Sharer.NET\bin\Release\*
    - name: zip Windows Forms
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerWindowsFormsExample.zip $Env:GITHUB_WORKSPACE\Sharer.NET Example - Windows Forms\bin\Release\*
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "SharerAsssemblies.zip"
        bodyFile: "Instructions.md"
        token: ${{ secrets.GITHUB_TOKEN }}
