name: CI

on: 
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: nuget/setup-nuget@v1
    - run: nuget restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln
    - name: Build
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        .\MSBuild.exe $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -p:Configuration=Release
    - name: zip Assemblies
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerAsssemblies.zip $Env:GITHUB_WORKSPACE\Sharer.NET\bin\Release\*
    - name: zip Windows Forms
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerWindowsFormsExample.zip "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Windows Forms\bin\Release\*"
    - name: Build Console examples
      run: |
        cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r win-x86
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=win-x86 /p:Configuration=Release /p:OutDir=bin/win-x86
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r win-x64
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=win-x64 /p:Configuration=Release /p:OutDir=bin/win-x64
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r win-arm
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=win-arm /p:Configuration=Release /p:OutDir=bin/win-arm
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r osx-x64
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=osx-x64 /p:Configuration=Release /p:OutDir=bin/osx-x64
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r linux-arm
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=linux-arm /p:Configuration=Release /p:OutDir=bin/linux-arm
        dotnet restore $Env:GITHUB_WORKSPACE\Sharer_VS2019.sln -r linux-x64
        .\MSBuild.exe "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\Sharer.NET Example - Console.csproj" /p:DeployOnBuild=true /p:PublishProfile=linux-x64 /p:Configuration=Release /p:OutDir=bin/linux-x64
    - name: zip win-x64
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_win-x64.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\win-x64\*"
    - name: zip win-x86
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_win-x86.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\win-x86\*"
    - name: zip win-arm
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_win-arm.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\win-arm\*"
    - name: zip linux-x64
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_linux-x64.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\linux-x64\*"
    - name: zip linux-arm
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_linux-arm.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\linux-arm\*"
    - name: zip osx-x64
      run: 7z a -tzip -mx=9 $Env:GITHUB_WORKSPACE\SharerConsoleExample_osx-x64.zip  "$Env:GITHUB_WORKSPACE\Sharer.NET Example - Console\bin\osx-x64\*"
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "SharerAsssemblies.zip,SharerWindowsFormsExample.zip,SharerConsoleExample_win-x64.zip,SharerConsoleExample_win-x86.zip,SharerConsoleExample_win-arm.zip,SharerConsoleExample_linux-x64.zip,SharerConsoleExample_linux-arm.zip,SharerConsoleExample_osx-x64.zip"
        bodyFile: "Instructions.md"
        token: ${{ secrets.GITHUB_TOKEN }}
